apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app.kubernetes.io/name: nginx-service
  ports:
    - name: "80"
      protocol: TCP
      port: 80
      targetPort: http-web-svc
    - name: "443"
      protocol: TCP
      port: 443
      targetPort: https-web-svc
