apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx
      app.kubernetes.io/name: nginx-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: nginx
        app.kubernetes.io/name: nginx-service
    spec:
      containers:
        - image: nginx:alpine
          name: nginx
          ports:
            - containerPort: 80
              name: http-web-svc
            - containerPort: 443
              name: https-web-svc
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
      restartPolicy: Always
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
            items:
              - key: nginx.conf
                path: nginx.conf
