name: Go Build for Red Hat

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - os-version: "7"
            container: centos:7  # Using CentOS 7 as a close proxy for RHEL 7
            install-cmd: "yum install -y golang libpcap-devel"
          - os-version: "9"
            container: registry.access.redhat.com/ubi9/ubi:latest  # UBI 9 for RHEL 9
            install-cmd: "yum install -y golang libpcap-devel"

    steps:
    - uses: actions/checkout@v2

    - name: Build on RHEL ${{ matrix.os-version }}
      run: |
        echo "Building for Red Hat Enterprise Linux version ${matrix.os-version}"
        docker run --rm -v $PWD:/app -w /app ${matrix.container} /bin/bash -c "
          ${matrix.install-cmd};
          go build -v ./...
        "

    - name: Test
      run: go test -v ./...
