name: Go Multi-OS Build with libpcap

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.x]
        include:
         - os: redhat-7
           distro: "rhel/7"
         - os: debian-latest
           distro: 'debian/buster'
         - os: ubuntu-latest
           distro: 'ubuntu/latest'
         - os: ubuntu-20.04
           distro: 'ubuntu/20.04'
    steps:
      - uses: actions/checkout@v3

      - name: Install Libpcap
        run: sudo apt-get install -y build-essential golang-go libpcap-dev
        
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
  
      - name: Build binaries for ${{ matrix.os }}
        run: |
          mkdir -p binaries/${{ matrix.os }}
          go build -v -o ./binaries/${{ matrix.os }}/siegelistener
  
      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: siegelistener-${{ matrix.os }}-1.0.0
          path: binaries/${{ matrix.os }}

      
