name: Go Multi-OS Build with libpcap

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.x]
        include:
          - os: redhat-7
            docker-image: 'registry.access.redhat.com/ubi7/ubi:latest'
    steps:
      - uses: actions/checkout@v3

      - name: Set Docker Image
        id: set-docker-image
        run: echo "DOCKER_IMAGE=${{ matrix.docker-image }}" >> $GITHUB_ENV
      
      - name: Build in Docker for ${{ matrix.os }}
        run: |
          docker run --rm -v $PWD:/app -w /app ${{ env.DOCKER_IMAGE }} /bin/bash -c "
            yum install -y make gcc libpcap-devel;
            wget https://golang.org/dl/go1.21.0.linux-amd64.tar.gz
            sudo tar -C /usr/local -xzf go1.21.0.linux-amd64.tar.gz
            echo "export PATH=$PATH:/usr/local/go/bin" >> ~/.bash_profile
            echo "export GOPATH=$HOME/go" >> ~/.bash_profile
            source ~/.bash_profile
            go build -v -o ./binaries/siegelistener ./...
          "
  
      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: siegelistener-${{ matrix.os }}-1.0.0
          path: binaries/${{ matrix.os }}

      
