name: Go Multi-OS Build with libpcap

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.x]
        include:
          - os: redhat-7
            docker-image: 'registry.access.redhat.com/ubi7/ubi:latest'
          - os: debian-latest
            docker-image: 'debian:buster'
          - os: ubuntu-latest
            docker-image: 'ubuntu:latest'
    steps:
      - uses: actions/checkout@v3

      - name: Set Docker Image
        id: set-docker-image
        run: echo "DOCKER_IMAGE=${{ matrix.docker-image }}" >> $GITHUB_ENV
      
      - name: Build in Docker for ${{ matrix.os }}
        run: |
          docker run --rm -v $PWD:/app -w /app ${{ env.DOCKER_IMAGE }} /bin/bash -c "
            apt-get update && apt-get install -y build-essential libpcap-dev golang-go || yum update && yum install -y make gcc libpcap-devel golang;
            go build -v -o ./binaries/siegelistener ./...
          "
  
      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: siegelistener-${{ matrix.os }}-1.0.0
          path: binaries/${{ matrix.os }}

      
