name: Go Multi-OS Build with libpcap

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.21.x]
        include:
         - os: redhat-7
           distro: "rhel/7"
    steps:
      - uses: actions/checkout@v3

      - name: Install Libpcap
        run: sudo apt-get install -y build-essential golang-go libpcap-dev
        
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
  
      - name: Build for ${{ matrix.distro }}
        run: |
          echo "Building for ${GITHUB_WORKFLOW} on ${{ matrix.distro }}"
          mkdir binaries
          for d in $(go list -f '{{.Dir}}' ./... | grep '/cmd'); do
            go build -v -o binaries/$(basename $d) $d
          done
  
      - name: Test
        run: go test -v ./...

      - name: Upload binary as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: siegelistener-${{ matrix.os }}-${{ matrix.go-version }}
          path: ./binaries

      
